package app

import (
	"context"
	"database/sql"
	"log"
	"time"

	_ "github.com/lib/pq"
)

func GetConnection(dsnString string) *sql.DB {
	if dsnString == "" {
		return nil
	}

	db, err := sql.Open("postgres", dsnString)
	if err != nil {
		log.Fatal(err)
	}

	err = db.Ping()
	if err != nil {
		log.Fatal(err)
	}

	return db
}

func CreateShortURLTable(db *sql.DB) error {
	query := `CREATE TABLE IF NOT EXISTS short_url(id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, full_url varchar, short_url varchar)`
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_, err := db.ExecContext(ctx, query)
	if err != nil {
		return err
	}
	return nil
}
